// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrDO-8UB6tJ57MNh4PYzm1pl8Xa3WA1_E',
    appId: '1:967013239009:web:c250ec6ed421706a440fa0',
    messagingSenderId: '967013239009',
    projectId: 'khip01-portfolio',
    authDomain: 'khip01-portfolio.firebaseapp.com',
    databaseURL: 'https://khip01-portfolio-default-rtdb.firebaseio.com',
    storageBucket: 'khip01-portfolio.appspot.com',
    measurementId: 'G-Y0PXY8H0B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4O7Zyhf4r9Qb13J3g50vvgZ9OkLT_iBU',
    appId: '1:967013239009:android:9f9d58f609b52147440fa0',
    messagingSenderId: '967013239009',
    projectId: 'khip01-portfolio',
    databaseURL: 'https://khip01-portfolio-default-rtdb.firebaseio.com',
    storageBucket: 'khip01-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWGpe2Z67jSOhm4Qte1CUCVneaIk5GSfQ',
    appId: '1:967013239009:ios:c57973d0334ea697440fa0',
    messagingSenderId: '967013239009',
    projectId: 'khip01-portfolio',
    databaseURL: 'https://khip01-portfolio-default-rtdb.firebaseio.com',
    storageBucket: 'khip01-portfolio.appspot.com',
    iosBundleId: 'com.example.me',
  );
}
